"""QA Manager projections and actions for the existing single-project application."""
import json
from collections import Counter, defaultdict
from datetime import datetime, timezone, timedelta
from flask import g, session
from werkzeug.security import check_password_hash, generate_password_hash
REVIEW_STATUSES = ('Pending', 'In Review', 'Approved', 'Needs Revision')
RISK_LEVELS = ('Low', 'Medium', 'High', 'Critical')
OPEN_STATUSES = ('Pending', 'In Review', 'Needs Revision')
QUALITY_KEYS = ('ambiguity', 'missing_information', 'testability', 'conflicts', 'missing_criteria', 'missing_tests', 'high_risk', 'refinement', 'attention', 'analyzed', 'traceability_gaps', 'reviewed', 'traceable', 'has_criteria', 'has_tests')

def utc_now():
    return datetime.now(timezone.utc)

def timestamp():
    return utc_now().isoformat(timespec='milliseconds')

def parse_time(value):
    try:
        result = datetime.fromisoformat(str(value).replace('Z', '+00:00'))
        return result.replace(tzinfo=timezone.utc) if result.tzinfo is None else result
    except (ValueError, TypeError):
        return None
PERMISSIONS = ('manage_users', 'manage_invitations', 'manage_permissions', 'assign_reviewers', 'manage_settings', 'create_requirements', 'review_requirements')
DEFAULT_PERMISSIONS = {'Manager': PERMISSIONS[:5], 'Analyst': ('create_requirements',), 'SQA Engineer': ('review_requirements',)}

def initialize_management_schema(connection):
    connection.execute('CREATE TABLE IF NOT EXISTS role_permissions (role TEXT NOT NULL, permission TEXT NOT NULL, enabled INTEGER NOT NULL, PRIMARY KEY(role,permission))')
    for role, defaults in DEFAULT_PERMISSIONS.items():
        for permission in PERMISSIONS:
            connection.execute('INSERT INTO role_permissions(role,permission,enabled) VALUES(?,?,?) ON CONFLICT(role,permission) DO NOTHING', (role, permission, int(permission in defaults)))
    additions = {'users': {'is_active': 'INTEGER NOT NULL DEFAULT 1', 'auth_version': 'INTEGER NOT NULL DEFAULT 0'}, 'requirements': {'assigned_reviewer_user_id': 'BIGINT REFERENCES users(id)'}}
    for table, columns in additions.items():
        existing = set()
        if connection.dialect == 'sqlite':
            existing = {row['name'] for row in connection.execute(f'PRAGMA table_info({table})')}
        for name, definition in columns.items():
            if connection.dialect == 'postgres':
                connection.execute(f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {name} {definition}')
            elif name not in existing:
                connection.execute(f'ALTER TABLE {table} ADD COLUMN {name} {definition}')
    identity = 'BIGINT GENERATED BY DEFAULT AS IDENTITY' if connection.dialect == 'postgres' else 'INTEGER'
    connection.execute(f'CREATE TABLE IF NOT EXISTS activity_events (\n        id {identity} PRIMARY KEY, actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,\n        actor_name TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL,\n        entity_id BIGINT, summary TEXT NOT NULL, created_at TEXT NOT NULL)')
    connection.execute('CREATE TABLE IF NOT EXISTS organization_settings (id INTEGER PRIMARY KEY, name TEXT NOT NULL, overdue_days INTEGER NOT NULL DEFAULT 7)')
    connection.execute("INSERT INTO organization_settings(id,name,overdue_days) VALUES(1,'ReqQuality AI',7) ON CONFLICT(id) DO NOTHING")
    connection.execute('CREATE INDEX IF NOT EXISTS idx_requirement_assignee ON requirements(assigned_reviewer_user_id)')
    connection.execute('CREATE INDEX IF NOT EXISTS idx_activity_created ON activity_events(created_at)')
    connection.commit()

def record_activity(connection, actor, action, entity_type, entity_id, summary):
    connection.execute('INSERT INTO activity_events(actor_id,actor_name,action,entity_type,entity_id,summary,created_at) VALUES(?,?,?,?,?,?,?)', (actor['id'] if actor else None, actor['name'] if actor else 'Invited user', action, entity_type, entity_id, summary, timestamp()))

class DashboardError(Exception):

    def __init__(self, message, status=400):
        self.message, self.status = (message, status)

def parse_filters(args):
    allowed = {'project', 'type', 'risk', 'review', 'reviewer', 'from', 'to', 'q', 'quality', 'page', 'page_size'}
    if set(args) - allowed:
        raise DashboardError('Unknown dashboard filter.')
    filters = {key: args.get(key, '').strip() for key in allowed}
    choices = {'project': {'', 'current'}, 'type': {'', 'Functional', 'Non-Functional', 'Business'}, 'risk': {'', *RISK_LEVELS, 'high-critical', 'unscored'}, 'review': {'', *REVIEW_STATUSES, 'pending-reviews'}, 'quality': {'', *QUALITY_KEYS}}
    for key, values in choices.items():
        if filters[key] not in values:
            raise DashboardError(f'Invalid {key} filter.')
    if filters['reviewer'] and filters['reviewer'] != 'unassigned':
        if not filters['reviewer'].isascii() or not filters['reviewer'].isdigit() or len(filters['reviewer']) > 19 or (int(filters['reviewer']) < 1):
            raise DashboardError('Invalid reviewer filter.')
    for key in ('from', 'to'):
        if filters[key]:
            try:
                parsed = datetime.strptime(filters[key], '%Y-%m-%d')
                if parsed.strftime('%Y-%m-%d') != filters[key]:
                    raise ValueError
            except ValueError:
                raise DashboardError('Dates must use YYYY-MM-DD.')
    if filters['from'] and filters['to'] and (filters['from'] > filters['to']):
        raise DashboardError('Start date must be on or before end date.')
    if len(filters['q']) > 200:
        raise DashboardError('Search must be 200 characters or fewer.')
    for key, default, maximum in [('page', 1, 100000), ('page_size', 20, 100)]:
        try:
            filters[key] = int(filters[key] or default)
            if not 1 <= filters[key] <= maximum:
                raise ValueError
        except ValueError:
            raise DashboardError(f'Invalid {key}.')
    return filters

def load_requirements(connection, overdue_days):
    rows = connection.execute('SELECT r.id,r.title,r.requirement_type,r.risk_level,r.risk_score,\n        r.review_status,r.created_at,r.updated_at,r.reviewed_at,r.reviewed_by_user_id,\n        r.assigned_reviewer_user_id,r.analysis_summary,\n        creator.name AS submitted_by,reviewer.name AS assigned_reviewer,\n        COALESCE(ac.count,0) AS criteria_count,COALESCE(ts.count,0) AS scenario_count\n        FROM requirements r LEFT JOIN users creator ON creator.id=r.created_by_user_id\n        LEFT JOIN users reviewer ON reviewer.id=r.assigned_reviewer_user_id\n        LEFT JOIN (SELECT requirement_id,COUNT(*) AS count FROM requirement_acceptance_criteria GROUP BY requirement_id) ac ON ac.requirement_id=r.id\n        LEFT JOIN (SELECT requirement_id,COUNT(*) AS count FROM test_scenarios GROUP BY requirement_id) ts ON ts.requirement_id=r.id\n        ORDER BY r.id DESC').fetchall()
    result = []
    cutoff = utc_now() - timedelta(days=overdue_days)
    for source in rows:
        row = dict(source)
        try:
            analysis = json.loads(row.pop('analysis_summary') or '{}')
            if not isinstance(analysis, dict):
                analysis = {}
        except (ValueError, TypeError):
            analysis = {}
        has = lambda key: isinstance(analysis.get(key), list) and bool(analysis[key])
        created = parse_time(row['created_at'])
        row['review_status'] = row['review_status'] or 'Pending'
        flags = {'ambiguity': has('ambiguity_issues'), 'missing_information': has('missing_information'), 'testability': has('testability_issues'), 'conflicts': has('conflict_issues') or has('inconsistency_issues'), 'missing_criteria': row['criteria_count'] == 0, 'missing_tests': row['scenario_count'] == 0, 'has_criteria': row['criteria_count'] > 0, 'has_tests': row['scenario_count'] > 0, 'high_risk': row['risk_level'] in ('High', 'Critical'), 'analyzed': row['risk_score'] is not None or bool(analysis), 'reviewed': bool(row['reviewed_at']), 'traceable': row['criteria_count'] > 0 and row['scenario_count'] > 0}
        flags['traceability_gaps'] = not flags['traceable']
        flags['refinement'] = row['review_status'] == 'Needs Revision' or any((flags[key] for key in ('ambiguity', 'missing_information', 'testability', 'conflicts', 'high_risk')))
        row['overdue'] = bool(created and created <= cutoff and (row['review_status'] in ('Pending', 'In Review')))
        reasons = []
        if flags['high_risk']:
            reasons.append(f"{row['risk_level']} risk")
        if row['overdue']:
            reasons.append(f'Review waiting {overdue_days}+ days')
        if row['review_status'] == 'Needs Revision':
            reasons.append('Needs revision')
        if flags['missing_criteria']:
            reasons.append('Missing acceptance criteria')
        if flags['missing_tests']:
            reasons.append('Missing test scenarios')
        if not reasons and flags['refinement']:
            reasons.append('Analysis findings need refinement')
        flags['attention'] = bool(reasons)
        row.update(project='ReqQuality AI', attention_reasons=reasons, quality_flags=flags, conflict_assessed=any((key in analysis for key in ('conflict_issues', 'inconsistency_issues'))))
        result.append(row)
    return result

def filter_requirements(rows, filters):

    def matches(row):
        if filters['type'] and row['requirement_type'] != filters['type']:
            return False
        risk = filters['risk']
        if risk == 'high-critical' and (not row['quality_flags']['high_risk']):
            return False
        if risk == 'unscored' and row['risk_level'] in RISK_LEVELS:
            return False
        if risk in RISK_LEVELS and row['risk_level'] != risk:
            return False
        review = filters['review']
        if review == 'pending-reviews' and row['review_status'] not in ('Pending', 'In Review'):
            return False
        if review in REVIEW_STATUSES and row['review_status'] != review:
            return False
        reviewer = filters['reviewer']
        if reviewer == 'unassigned' and row['assigned_reviewer_user_id'] is not None:
            return False
        if reviewer.isdigit() and row['assigned_reviewer_user_id'] != int(reviewer):
            return False
        created = parse_time(row['created_at'])
        date = created.astimezone(timezone.utc).date().isoformat() if created else ''
        if filters['from'] and (not date or date < filters['from']):
            return False
        if filters['to'] and (not date or date > filters['to']):
            return False
        if filters['q'] and filters['q'].casefold() not in f"REQ-{row['id']} {row['title']}".casefold():
            return False
        if filters['quality'] and (not row['quality_flags'][filters['quality']]):
            return False
        return True
    return [row for row in rows if matches(row)]

def build_dashboard(connection, filters):
    settings = dict(connection.execute('SELECT name,overdue_days FROM organization_settings WHERE id=1').fetchone())
    rows = filter_requirements(load_requirements(connection, settings['overdue_days']), filters)
    total = len(rows)
    count = lambda flag: sum((row['quality_flags'][flag] for row in rows))
    review_counts = Counter((row['review_status'] for row in rows))
    risk_counts = Counter((row['risk_level'] or 'Unscored' for row in rows))
    percent = lambda value: round(100 * value / total, 1) if total else 0
    team = [dict(row) for row in connection.execute('SELECT id,name,email,role,is_active,created_at FROM users ORDER BY name,id')]
    workload = []
    for member in team:
        assigned = [row for row in rows if row['assigned_reviewer_user_id'] == member['id']]
        member['workload'] = sum((row['review_status'] in OPEN_STATUSES for row in assigned))
        member['status'] = 'Active' if member.pop('is_active') else 'Disabled'
        if member['role'] == 'SQA Engineer':
            workload.append({'id': member['id'], 'name': member['name'], 'status': member['status'], 'assigned': len(assigned), 'pending': member['workload'], 'completed': sum((row['reviewed_by_user_id'] == member['id'] and row['review_status'] == 'Approved' for row in rows)), 'high_risk': sum((row['quality_flags']['high_risk'] and row['review_status'] in OPEN_STATUSES for row in assigned))})
    invitation_rows = connection.execute('SELECT id,name,email,role,status,expires_at FROM user_invitations').fetchall()
    invitation_counts = Counter()
    invited = []
    for row in invitation_rows:
        expiry = parse_time(row['expires_at'])
        status = 'expired' if row['status'] == 'pending' and expiry and (expiry <= utc_now()) else row['status']
        invitation_counts[status] += 1
        if status == 'pending':
            invited.append({key: row[key] for key in ('id', 'name', 'email', 'role')})
    activity = [dict(row) for row in connection.execute('SELECT id,actor_name,action,entity_type,entity_id,summary,created_at FROM activity_events ORDER BY created_at DESC,id DESC LIMIT 50')]
    cohorts = defaultdict(list)
    for row in rows:
        created = parse_time(row['created_at'])
        if created:
            cohorts[created.strftime('%Y-%m')].append(row)
    trends = []
    for month in sorted(cohorts)[-6:]:
        cohort = cohorts[month]
        scores = [row['risk_score'] for row in cohort if row['risk_score'] is not None]
        trends.append({'month': month, 'count': len(cohort), 'average_risk': round(sum(scores) / len(scores), 1) if scores else None, 'approved': sum((row['review_status'] == 'Approved' for row in cohort))})
    attention = sorted((row for row in rows if row['quality_flags']['attention']), key=lambda row: (0 if row['risk_level'] == 'Critical' else 1 if row['risk_level'] == 'High' else 2, not row['overdue'], row['created_at'] or '', row['id']))
    pending = sorted((row for row in rows if row['review_status'] in ('Pending', 'In Review')), key=lambda row: (row['assigned_reviewer_user_id'] is not None, row['created_at'] or '', row['id']))
    return {'organization': settings, 'project': {'id': 'current', 'name': 'ReqQuality AI'}, 'summary': {'total': total, 'analyzed': count('analyzed'), 'pending_reviews': len(pending), 'approved': review_counts['Approved'], 'high_risk': count('high_risk'), 'needs_revision': review_counts['Needs Revision'], 'unassigned': sum((row['assigned_reviewer_user_id'] is None for row in pending)), 'overdue': sum((row['overdue'] for row in rows))}, 'review_distribution': [{'label': 'Not Reviewed' if key == 'Pending' else key, 'value': key, 'count': review_counts[key], 'percent': percent(review_counts[key])} for key in REVIEW_STATUSES], 'risk_distribution': [{'label': key, 'value': key, 'count': risk_counts[key], 'percent': percent(risk_counts[key])} for key in RISK_LEVELS], 'unscored': sum((row['risk_level'] not in RISK_LEVELS for row in rows)), 'quality': {key: count(key) for key in QUALITY_KEYS}, 'conflicts_available': any((row['conflict_assessed'] for row in rows)), 'traceability': {'with_criteria': total - count('missing_criteria'), 'with_tests': total - count('missing_tests'), 'reviewed': count('reviewed'), 'fully_traceable': count('traceable'), 'missing_links': count('traceability_gaps'), 'coverage': percent(count('traceable'))}, 'attention': attention[:8], 'attention_total': len(attention), 'pending_reviews': pending[:8], 'team': team, 'team_summary': {'total': len(team), 'analysts': sum((row['role'] == 'Analyst' for row in team)), 'engineers': len(workload), 'active': sum((row['status'] == 'Active' for row in team))}, 'invitations': {status: invitation_counts[status] for status in ('pending', 'accepted', 'expired', 'revoked')}, 'invited_members': invited, 'reviewer_workload': workload, 'activity': activity, 'trends': trends, 'scope_note': 'Requirement filters apply to quality, review, traceability, trends and workload. Team, invitations and activity are organization-wide.'}
from types import SimpleNamespace
from services.responses import response_payload

def create_services(app, get_connection, roles_required, csrf_required, login_required):

    def get_roles(connection):
        return response_payload(permissions=list(PERMISSIONS), roles={role: {row['permission']: bool(row['enabled']) for row in connection.execute('SELECT permission,enabled FROM role_permissions WHERE role=?', (role,))} for role in DEFAULT_PERMISSIONS})

    def update_role(connection, role, payload):
        data = payload
        if role not in DEFAULT_PERMISSIONS or not isinstance(data, dict) or (not data) or any((key not in PERMISSIONS or type(value) is not bool for key, value in data.items())):
            raise DashboardError('Provide a supported role and boolean permissions.')
        for permission, enabled in data.items():
            connection.execute('UPDATE role_permissions SET enabled=? WHERE role=? AND permission=?', (int(enabled), role, permission))
        record_activity(connection, g.current_user, 'permissions_updated', 'role', None, f'Updated permissions for {role}')
        return response_payload(message='Role permissions saved.')

    def manager_dashboard(connection, query_params):
        return response_payload(build_dashboard(connection, parse_filters(query_params)))

    def manager_requirements(connection, query_params):
        filters = parse_filters(query_params)
        settings = connection.execute('SELECT overdue_days FROM organization_settings WHERE id=1').fetchone()
        rows = filter_requirements(load_requirements(connection, settings['overdue_days']), filters)
        start = (filters['page'] - 1) * filters['page_size']
        return response_payload(requirements=rows[start:start + filters['page_size']], total=len(rows), page=filters['page'], page_size=filters['page_size'])

    def assign_reviewer(connection, requirement_id, payload):
        data = payload
        if not isinstance(data, dict) or set(data) != {'reviewer_id'}:
            raise DashboardError('Choose a reviewer or Unassigned.')
        reviewer_id = data['reviewer_id']
        suffix = ' FOR UPDATE' if connection.dialect == 'postgres' else ''
        if reviewer_id is not None:
            if type(reviewer_id) is not int or reviewer_id < 1:
                raise DashboardError('Choose an active SQA Engineer.')
            reviewer = connection.execute('SELECT id,name,role,is_active FROM users WHERE id=?' + suffix, (reviewer_id,)).fetchone()
            if not reviewer or reviewer['role'] != 'SQA Engineer' or (not reviewer['is_active']):
                raise DashboardError('Choose an active SQA Engineer.')
        row = connection.execute('SELECT id,assigned_reviewer_user_id FROM requirements WHERE id=?' + suffix, (requirement_id,)).fetchone()
        if not row:
            raise DashboardError('Requirement not found.', 404)
        if row['assigned_reviewer_user_id'] != reviewer_id:
            connection.execute('UPDATE requirements SET assigned_reviewer_user_id=?,updated_at=? WHERE id=?', (reviewer_id, timestamp(), requirement_id))
            summary = f"Assigned REQ-{requirement_id} to {reviewer['name']}" if reviewer_id else f'Unassigned REQ-{requirement_id}'
            record_activity(connection, g.current_user, 'reviewer_assigned', 'requirement', requirement_id, summary)
        return response_payload(message='Reviewer assignment saved.')

    def manage_member(connection, user_id, payload):
        data = payload
        if not isinstance(data, dict) or not data or set(data) - {'role', 'is_active'}:
            raise DashboardError('Provide a supported role or active status.')
        suffix = ' FOR UPDATE' if connection.dialect == 'postgres' else ''
        member = connection.execute('SELECT id,name,role,is_active FROM users WHERE id=?' + suffix, (user_id,)).fetchone()
        if not member:
            raise DashboardError('Team member not found.', 404)
        if member['role'] == 'admin':
            raise DashboardError('QA Manager accounts cannot be changed from team management.', 403)
        if user_id == g.current_user['id']:
            raise DashboardError('You cannot change your own role or active status.', 403)
        role, active = (data.get('role', member['role']), data.get('is_active', bool(member['is_active'])))
        if role not in ('Manager', 'Analyst', 'SQA Engineer') or type(active) is not bool:
            raise DashboardError('Choose Manager, Analyst or SQA Engineer and a valid active status.')
        if role != member['role'] or active != bool(member['is_active']):
            connection.execute('UPDATE users SET role=?,is_active=?,auth_version=auth_version+1 WHERE id=?', (role, int(active), user_id))
            from services.token_service import revoke_user_tokens
            revoke_user_tokens(connection, user_id)
            if role != 'SQA Engineer' or not active:
                connection.execute("UPDATE requirements SET assigned_reviewer_user_id=NULL,updated_at=? WHERE assigned_reviewer_user_id=? AND review_status IN ('Pending','In Review','Needs Revision')", (timestamp(), user_id))
            record_activity(connection, g.current_user, 'member_updated', 'user', user_id, f"Updated {member['name']}: {role}, {('Active' if active else 'Disabled')}; open assignments cleared when ineligible")
        return response_payload(message='Team member updated. Existing sessions were invalidated.')

    def save_settings(connection, payload):
        data = payload
        if not isinstance(data, dict) or set(data) != {'name', 'overdue_days'}:
            raise DashboardError('Provide organization name and overdue review threshold.')
        name, days = (data['name'], data['overdue_days'])
        if not isinstance(name, str) or not 2 <= len(name.strip()) <= 100 or type(days) is not int or (not 1 <= days <= 90):
            raise DashboardError('Name must be 2-100 characters and overdue threshold 1-90 days.')
        connection.execute('UPDATE organization_settings SET name=?,overdue_days=? WHERE id=1', (name.strip(), days))
        record_activity(connection, g.current_user, 'settings_updated', 'organization', 1, 'Updated organization settings')
        return response_payload(message='Organization settings saved.')

    def change_password(connection, payload):
        data = payload
        if not isinstance(data, dict) or not isinstance(data.get('current_password'), str) or (not isinstance(data.get('new_password'), str)):
            raise DashboardError('Enter your current and new passwords.')
        if not 12 <= len(data['new_password']) <= 128 or len(data['current_password']) > 128:
            raise DashboardError('New password must be between 12 and 128 characters.')
        suffix = ' FOR UPDATE' if connection.dialect == 'postgres' else ''
        user = connection.execute('SELECT password_hash FROM users WHERE id=?' + suffix, (g.current_user['id'],)).fetchone()
        if not check_password_hash(user['password_hash'], data['current_password']):
            raise DashboardError('Current password is incorrect.', 400)
        connection.execute('UPDATE users SET password_hash=?,auth_version=auth_version+1 WHERE id=?', (generate_password_hash(data['new_password'], method='scrypt'), g.current_user['id']))
        from services.token_service import revoke_user_tokens
        revoke_user_tokens(connection, g.current_user['id'])
        g.clear_auth_cookies = True
        record_activity(connection, g.current_user, 'password_changed', 'user', g.current_user['id'], 'Changed account password')
        session.clear()
        return response_payload(message='Password changed. Sign in again on all devices.')
    return SimpleNamespace(get_roles=get_roles, update_role=update_role, manager_dashboard=manager_dashboard, manager_requirements=manager_requirements, assign_reviewer=assign_reviewer, manage_member=manage_member, save_settings=save_settings, change_password=change_password)
