"""Small SQLite/PostgreSQL connection adapter for the Flask application."""

import re
import sqlite3
from pathlib import Path

import psycopg


def _postgres_row_factory(cursor):
    if cursor.description is None:
        return lambda values: DatabaseRow()
    columns = [column.name for column in cursor.description]

    def make_row(values):
        return DatabaseRow(zip(columns, values))

    return make_row


class DatabaseRow(dict):
    """Mapping row with SQLite-compatible positional access."""

    def __getitem__(self, key):
        if isinstance(key, int):
            return tuple(self.values())[key]
        return super().__getitem__(key)


class DatabaseConnection:
    def __init__(self, connection, dialect):
        self._connection = connection
        self.dialect = dialect

    def _adapt_sql(self, statement):
        if self.dialect == "postgres":
            return re.sub(r"\?", "%s", statement)
        return statement

    def execute(self, statement, parameters=()):
        return self._connection.execute(self._adapt_sql(statement), parameters)

    def executemany(self, statement, parameters):
        cursor = self._connection.cursor()
        cursor.executemany(self._adapt_sql(statement), parameters)
        return cursor

    def commit(self):
        self._connection.commit()

    def close(self):
        self._connection.close()

    def __enter__(self):
        self._connection.__enter__()
        return self

    def __exit__(self, exception_type, exception, traceback):
        return self._connection.__exit__(exception_type, exception, traceback)


def connect_database(database_url, sqlite_path):
    if database_url:
        normalized_url = database_url.strip()
        if normalized_url.startswith("postgres://"):
            normalized_url = "postgresql://" + normalized_url[len("postgres://"):]
        if normalized_url.startswith("postgresql+psycopg://"):
            normalized_url = "postgresql://" + normalized_url[len("postgresql+psycopg://"):]
        connection = psycopg.connect(normalized_url, row_factory=_postgres_row_factory)
        return DatabaseConnection(connection, "postgres")

    database_path = Path(sqlite_path)
    database_path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(database_path)
    connection.row_factory = sqlite3.Row
    return DatabaseConnection(connection, "sqlite")


DATABASE_ERRORS = (sqlite3.Error, psycopg.Error)
DATABASE_INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.IntegrityError)


def initialize_postgresql_schema(connection):
    statements = (
        "CREATE TABLE IF NOT EXISTS users ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, "
        "role TEXT NOT NULL CHECK(role IN ('Analyst', 'SQA Reviewer')), "
        "created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text))",
        "CREATE TABLE IF NOT EXISTS requirements ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "title TEXT NOT NULL, description TEXT NOT NULL, requirement_type TEXT NOT NULL, "
        "priority TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text), "
        "user_priority TEXT NOT NULL DEFAULT 'Medium', suggested_priority TEXT, "
        "risk_score INTEGER, risk_level TEXT, review_status TEXT NOT NULL DEFAULT 'Pending', "
        "reviewer_notes TEXT NOT NULL DEFAULT '', "
        "updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text), "
        "source TEXT NOT NULL DEFAULT 'original', needs_confirmation INTEGER NOT NULL DEFAULT 0, "
        "created_by_user_id BIGINT REFERENCES users(id), "
        "reviewed_by_user_id BIGINT REFERENCES users(id), reviewed_at TEXT, "
        "analysis_summary TEXT NOT NULL DEFAULT '{}')",
        "CREATE TABLE IF NOT EXISTS requirement_acceptance_criteria ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "requirement_id BIGINT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE, "
        "criterion_code TEXT NOT NULL, description TEXT NOT NULL, "
        "source TEXT NOT NULL DEFAULT 'ai_suggestion', "
        "needs_confirmation INTEGER NOT NULL DEFAULT 1, "
        "introduced_values TEXT NOT NULL DEFAULT '[]', "
        "UNIQUE(requirement_id, criterion_code))",
        "CREATE TABLE IF NOT EXISTS test_scenarios ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "requirement_id BIGINT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE, "
        "scenario_code TEXT NOT NULL, category TEXT NOT NULL, title TEXT NOT NULL, "
        "preconditions TEXT NOT NULL, test_steps TEXT NOT NULL, expected_result TEXT NOT NULL, "
        "source TEXT NOT NULL DEFAULT 'ai_suggestion', "
        "needs_confirmation INTEGER NOT NULL DEFAULT 1, "
        "introduced_values TEXT NOT NULL DEFAULT '[]', "
        "assumption_reasons TEXT NOT NULL DEFAULT '[]', UNIQUE(requirement_id, scenario_code))",
        "CREATE TABLE IF NOT EXISTS requirement_assumptions ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "requirement_id BIGINT NOT NULL REFERENCES requirements(id) ON DELETE CASCADE, "
        "assumption_code TEXT NOT NULL, description TEXT NOT NULL, "
        "source TEXT NOT NULL DEFAULT 'ai_assumption', "
        "needs_confirmation INTEGER NOT NULL DEFAULT 1, "
        "introduced_values TEXT NOT NULL DEFAULT '[]', "
        "UNIQUE(requirement_id, assumption_code))",
        "CREATE INDEX IF NOT EXISTS idx_requirements_created_by_user_id "
        "ON requirements(created_by_user_id)",
        "CREATE INDEX IF NOT EXISTS idx_requirements_reviewed_by_user_id "
        "ON requirements(reviewed_by_user_id)",
        "CREATE INDEX IF NOT EXISTS idx_criteria_requirement_id "
        "ON requirement_acceptance_criteria(requirement_id)",
        "CREATE INDEX IF NOT EXISTS idx_scenarios_requirement_id "
        "ON test_scenarios(requirement_id)",
        "CREATE INDEX IF NOT EXISTS idx_assumptions_requirement_id "
        "ON requirement_assumptions(requirement_id)",
    )
    for statement in statements:
        connection.execute(statement)
    connection.commit()
