"""Invitation lifecycle. Tokens and identity verification remain server controlled."""
import hashlib
import hmac
import os
import re
import secrets
import smtplib
import ssl
from datetime import datetime, timedelta, timezone
from email.message import EmailMessage
from functools import wraps
from urllib.parse import urlsplit

from flask import g, jsonify, request, session
from werkzeug.security import generate_password_hash
from database import DATABASE_ERRORS, DATABASE_INTEGRITY_ERRORS
from admin_dashboard import record_activity

ROLES = {'Analyst', 'SQA Engineer'}
EMAIL = re.compile(r'^[^\s@]+@[^\s@]+\.[^\s@]+$')
WINDOW = timedelta(minutes=15)


def now():
    return datetime.now(timezone.utc)


def stamp(value):
    return value.isoformat(timespec='microseconds')


def digest(token):
    return hashlib.sha256(token.encode()).hexdigest()


def migrate_sqlite_roles(connection):
    row = connection.execute("SELECT sql FROM sqlite_master WHERE name = 'users'").fetchone()
    if row and "'admin'" not in row['sql']:
        # The referenced table name stays users; disable FK checks only during rebuild.
        connection.execute('PRAGMA foreign_keys = OFF')
        with connection:
            connection.execute('BEGIN IMMEDIATE')
            current_schema = connection.execute("SELECT sql FROM sqlite_master WHERE name = 'users'").fetchone()
            if "'admin'" in current_schema['sql']:
                return
            connection.execute("CREATE TABLE users_role_migration (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE COLLATE NOCASE, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin', 'Analyst', 'SQA Engineer')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)")
            connection.execute("INSERT INTO users_role_migration SELECT id, name, email, password_hash, CASE WHEN role = 'SQA Reviewer' THEN 'SQA Engineer' ELSE role END, created_at FROM users")
            connection.execute('DROP TABLE users')
            connection.execute('ALTER TABLE users_role_migration RENAME TO users')


def initialize_invitations(connection):
    identity = 'BIGINT GENERATED BY DEFAULT AS IDENTITY' if connection.dialect == 'postgres' else 'INTEGER'
    connection.execute(f"""CREATE TABLE IF NOT EXISTS user_invitations (
        id {identity} PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL,
        role TEXT NOT NULL CHECK(role IN ('Analyst', 'SQA Engineer')),
        token_hash TEXT NOT NULL UNIQUE,
        status TEXT NOT NULL CHECK(status IN ('pending', 'accepted', 'expired', 'revoked')),
        failed_attempts INTEGER NOT NULL DEFAULT 0,
        window_failed_attempts INTEGER NOT NULL DEFAULT 0,
        failure_window_started_at TEXT, last_failed_attempt_at TEXT,
        temporarily_locked_until TEXT, created_at TEXT NOT NULL, expires_at TEXT NOT NULL,
        accepted_at TEXT, revoked_at TEXT, invited_by BIGINT NOT NULL REFERENCES users(id),
        delivery_status TEXT NOT NULL DEFAULT 'pending')""")
    connection.execute('CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_normalized ON users(lower(email))')
    connection.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_pending_invitation_email ON user_invitations(lower(email)) WHERE status = 'pending'")
    connection.commit()


def send_invitation(invitation, token):
    base = os.getenv('INVITATION_FRONTEND_URL', '').rstrip('/')
    parsed = urlsplit(base)
    if parsed.scheme not in {'http', 'https'} or not parsed.netloc or parsed.query or parsed.fragment:
        raise ValueError('Invalid frontend URL configuration')
    host = os.environ['SMTP_HOST']
    sender = os.environ['SMTP_FROM']
    message = EmailMessage()
    message['Subject'] = 'Your ReqQuality AI invitation'
    message['From'] = sender
    message['To'] = invitation['email']
    message.set_content(
        f"Hello {invitation['name']},\n\nYou have been invited to ReqQuality AI as an {invitation['role']}.\n"
        f"Open {base}/accept-invitation?token={token}\n\n"
        'This invitation expires after 24 hours and can only be successfully used once.\n'
        'Enter your invited email address, then set your password.\n')
    use_ssl = os.getenv('SMTP_SSL', 'false').lower() == 'true'
    transport = smtplib.SMTP_SSL if use_ssl else smtplib.SMTP
    options = {'timeout': 15}
    if use_ssl:
        options['context'] = ssl.create_default_context()
    with transport(host, int(os.getenv('SMTP_PORT', '465' if use_ssl else '587')), **options) as smtp:
        if not use_ssl:
            smtp.starttls(context=ssl.create_default_context())
        username = os.getenv('SMTP_USERNAME')
        if username:
            smtp.login(username, os.environ['SMTP_PASSWORD'])
        if smtp.send_message(message):
            raise RuntimeError('Recipient refused')


def public_invitation(row):
    return {key: row[key] for key in ('id', 'name', 'email', 'role', 'status', 'failed_attempts',
        'last_failed_attempt_at', 'temporarily_locked_until', 'created_at', 'expires_at',
        'accepted_at', 'revoked_at', 'invited_by', 'delivery_status')}


class InvitationError(Exception):
    def __init__(self, message, code=400):
        self.message, self.code = message, code


def begin_write(connection):
    if connection.dialect == 'sqlite':
        connection.execute('BEGIN IMMEDIATE')


def expire_pending(connection):
    connection.execute("UPDATE user_invitations SET status = 'expired' WHERE status = 'pending' AND expires_at <= ?", (stamp(now()),))


def lookup(connection, token):
    if not isinstance(token, str) or not 40 <= len(token) <= 128:
        raise InvitationError('Invalid invitation.')
    suffix = ' FOR UPDATE' if connection.dialect == 'postgres' else ''
    row = connection.execute('SELECT * FROM user_invitations WHERE token_hash = ?' + suffix, (digest(token),)).fetchone()
    if row is None:
        raise InvitationError('Invalid invitation.')
    if row['status'] == 'accepted':
        raise InvitationError('This invitation has already been used.', 410)
    if row['status'] == 'revoked':
        raise InvitationError('This invitation has been revoked.', 410)
    if row['status'] == 'expired' or now() >= datetime.fromisoformat(row['expires_at']):
        connection.execute("UPDATE user_invitations SET status = 'expired' WHERE id = ?", (row['id'],))
        raise InvitationError('This invitation has expired.', 410)
    return row


def register_invitation_routes(app, get_connection, roles_required, csrf_required):
    # Commit expected validation failures too: expiry and failed attempts are durable.
    def database_action(view):
        @wraps(view)
        def wrapped(*args, **kwargs):
            connection = get_connection()
            try:
                with connection:
                    begin_write(connection)
                    try:
                        return view(connection, *args, **kwargs)
                    except InvitationError as error:
                        return jsonify(error=error.message), error.code
            except DATABASE_INTEGRITY_ERRORS:
                return jsonify(error='An account or pending invitation already exists.'), 409
            except DATABASE_ERRORS:
                app.logger.error('Invitation database operation failed')
                return jsonify(error='Unable to complete this request. Please try again.'), 503
            finally:
                connection.close()
        return wrapped

    def deliver(connection, row, token):
        try:
            send_invitation(row, token)
        except Exception:
            # Never log SMTP exceptions: their text can contain message bodies/tokens.
            app.logger.warning('Invitation email delivery failed invitation_id=%s', row['id'])
            connection.execute("UPDATE user_invitations SET delivery_status = 'failed' WHERE id = ?", (row['id'],))
            record_activity(connection, g.current_user, 'invitation_delivery_failed', 'invitation', row['id'], 'Invitation saved; email delivery failed')
            return jsonify(error='Invitation saved, but email delivery failed. Check email configuration and resend.', invitation_id=row['id']), 502
        connection.execute("UPDATE user_invitations SET delivery_status = 'sent' WHERE id = ?", (row['id'],))
        record_activity(connection, g.current_user, 'invitation_sent', 'invitation', row['id'], 'Invitation sent or regenerated')
        return jsonify(message='Invitation saved and email sent.', invitation_id=row['id']), 201

    @app.get('/api/admin/invitations')
    @roles_required('admin')
    @database_action
    def list_invitations(connection):
        expire_pending(connection)
        rows = connection.execute('SELECT * FROM user_invitations ORDER BY id DESC').fetchall()
        return jsonify(invitations=[public_invitation(row) for row in rows])

    @app.get('/api/admin/invitations/<int:invitation_id>')
    @roles_required('admin')
    @database_action
    def view_invitation(connection, invitation_id):
        expire_pending(connection)
        row = connection.execute('SELECT * FROM user_invitations WHERE id = ?', (invitation_id,)).fetchone()
        if not row:
            raise InvitationError('Invitation not found.', 404)
        return jsonify(invitation=public_invitation(row))

    @app.post('/api/admin/invitations')
    @roles_required('admin')
    @csrf_required
    @database_action
    def create_invitation(connection):
        data = request.get_json(silent=True)
        if not isinstance(data, dict):
            raise InvitationError('Send valid invitation details.')
        name, email, role = data.get('name'), data.get('email'), data.get('role')
        if not isinstance(name, str) or not 2 <= len(name.strip()) <= 80 or any(ord(c) < 32 for c in name):
            raise InvitationError('Name must be between 2 and 80 characters.')
        if not isinstance(email, str) or len(email.strip()) > 254 or not EMAIL.fullmatch(email.strip()):
            raise InvitationError('Enter a valid email address.')
        if not isinstance(role, str) or role not in ROLES:
            raise InvitationError('Choose SQA Engineer or Analyst.')
        email = email.strip().lower()
        expire_pending(connection)
        if connection.execute('SELECT id FROM users WHERE lower(email) = ?', (email,)).fetchone():
            raise InvitationError('An account already exists for this email.', 409)
        if connection.execute("SELECT id FROM user_invitations WHERE lower(email) = ? AND status = 'pending'", (email,)).fetchone():
            raise InvitationError('A pending invitation already exists for this email.', 409)
        token, created = secrets.token_urlsafe(32), now()
        sql = "INSERT INTO user_invitations (name,email,role,token_hash,status,created_at,expires_at,invited_by) VALUES (?,?,?,?,'pending',?,?,?)"
        if connection.dialect == 'postgres':
            sql += ' RETURNING id'
        cursor = connection.execute(sql, (name.strip(), email, role, digest(token), stamp(created), stamp(created + timedelta(hours=24)), g.current_user['id']))
        invitation_id = cursor.fetchone()['id'] if connection.dialect == 'postgres' else cursor.lastrowid
        row = connection.execute('SELECT * FROM user_invitations WHERE id = ?', (invitation_id,)).fetchone()
        return deliver(connection, row, token)

    def admin_row(connection, invitation_id):
        expire_pending(connection)
        suffix = ' FOR UPDATE' if connection.dialect == 'postgres' else ''
        row = connection.execute('SELECT * FROM user_invitations WHERE id = ?' + suffix, (invitation_id,)).fetchone()
        if not row:
            raise InvitationError('Invitation not found.', 404)
        return row

    @app.post('/api/admin/invitations/<int:invitation_id>/revoke')
    @roles_required('admin')
    @csrf_required
    @database_action
    def revoke_invitation(connection, invitation_id):
        row = admin_row(connection, invitation_id)
        if row['status'] != 'pending':
            raise InvitationError('Only pending invitations can be revoked.', 409)
        connection.execute("UPDATE user_invitations SET status = 'revoked', revoked_at = ? WHERE id = ?", (stamp(now()), invitation_id))
        record_activity(connection, g.current_user, 'invitation_revoked', 'invitation', invitation_id, 'Revoked invitation')
        return jsonify(message='Invitation revoked.')

    @app.post('/api/admin/invitations/<int:invitation_id>/resend')
    @roles_required('admin')
    @csrf_required
    @database_action
    def resend_invitation(connection, invitation_id):
        row = admin_row(connection, invitation_id)
        if row['status'] == 'accepted' or connection.execute('SELECT id FROM users WHERE lower(email) = ?', (row['email'],)).fetchone():
            raise InvitationError('This invitation cannot be resent.', 409)
        # Revocation is deliberately not undone; create a new invitation instead.
        if row['status'] == 'revoked':
            raise InvitationError('Create a new invitation for this revoked invitation.', 409)
        token, created = secrets.token_urlsafe(32), now()
        connection.execute("UPDATE user_invitations SET token_hash = ?, status = 'pending', created_at = ?, expires_at = ?, invited_by = ?, failed_attempts = 0, window_failed_attempts = 0, failure_window_started_at = NULL, last_failed_attempt_at = NULL, temporarily_locked_until = NULL, delivery_status = 'pending' WHERE id = ?", (digest(token), stamp(created), stamp(created + timedelta(hours=24)), g.current_user['id'], invitation_id))
        return deliver(connection, row, token)

    @app.post('/api/invitations/validate')
    @database_action
    def validate_invitation(connection):
        data = request.get_json(silent=True) or {}
        row = lookup(connection, data.get('token') if isinstance(data, dict) else None)
        return jsonify(valid=True, expires_at=row['expires_at'])

    @app.post('/api/invitations/verify-email')
    @database_action
    def verify_email(connection):
        data = request.get_json(silent=True) or {}
        if not isinstance(data, dict):
            raise InvitationError('Invalid invitation.')
        row = lookup(connection, data.get('token'))
        current = now()
        if row['temporarily_locked_until'] and current < datetime.fromisoformat(row['temporarily_locked_until']):
            raise InvitationError('Too many verification attempts. Temporarily locked; try again after 15 minutes.', 429)
        email = data.get('email')
        normalized = email.strip().lower() if isinstance(email, str) else ''
        if len(normalized) > 254 or not EMAIL.fullmatch(normalized) or not hmac.compare_digest(normalized.encode(), row['email'].encode()):
            count = row['window_failed_attempts']
            started = row['failure_window_started_at']
            if not started or current >= datetime.fromisoformat(started) + WINDOW:
                started, count = stamp(current), 0
            count += 1
            locked = stamp(current + WINDOW) if count >= 5 else None
            connection.execute('UPDATE user_invitations SET failed_attempts = failed_attempts + 1, window_failed_attempts = ?, failure_window_started_at = ?, last_failed_attempt_at = ?, temporarily_locked_until = ? WHERE id = ?', (count, started, stamp(current), locked, row['id']))
            app.logger.info('Invitation verification mismatch invitation_id=%s', row['id'])
            if locked:
                raise InvitationError('Too many verification attempts. Temporarily locked; try again after 15 minutes.', 429)
            raise InvitationError('The provided information does not match this invitation.')
        session['verified_invitation'] = {'id': row['id'], 'token_hash': row['token_hash']}
        session['invitation_csrf'] = secrets.token_urlsafe(32)
        return jsonify(verified=True, message='Email verified. Set your password to complete registration.', csrf_token=session['invitation_csrf'])

    @app.post('/api/invitations/accept')
    @database_action
    def accept_invitation(connection):
        data = request.get_json(silent=True) or {}
        if not isinstance(data, dict):
            raise InvitationError('Invalid invitation.')
        row = lookup(connection, data.get('token'))
        verified = session.get('verified_invitation')
        csrf = request.headers.get('X-CSRF-Token', '')
        if not verified or verified != {'id': row['id'], 'token_hash': row['token_hash']} or not csrf or not hmac.compare_digest(csrf.encode(), session.get('invitation_csrf', '').encode()):
            raise InvitationError('Verify your invited email before creating an account.', 403)
        if any(key in data for key in ('role', 'email', 'name', 'status', 'expires_at', 'invited_by')):
            raise InvitationError('Account details are assigned by your invitation.')
        password = data.get('password')
        if not isinstance(password, str) or not 12 <= len(password) <= 128:
            raise InvitationError('Password must be between 12 and 128 characters.')
        if connection.execute('SELECT id FROM users WHERE lower(email) = ?', (row['email'],)).fetchone():
            raise InvitationError('Unable to create this account.', 409)
        password_hash = generate_password_hash(password, method='scrypt')
        row = lookup(connection, data.get('token'))
        connection.execute('INSERT INTO users (name,email,password_hash,role) VALUES (?,?,?,?)', (row['name'], row['email'], password_hash, row['role']))
        connection.execute("UPDATE user_invitations SET status = 'accepted', accepted_at = ? WHERE id = ?", (stamp(now()), row['id']))
        joined = connection.execute('SELECT id,name FROM users WHERE lower(email)=?', (row['email'],)).fetchone()
        record_activity(connection, joined, 'invitation_accepted', 'invitation', row['id'], f"Joined as {row['role']}")
        session.clear()
        return jsonify(message='Account created successfully. Please sign in.'), 201

    @app.after_request
    def invitation_privacy(response):
        if request.path.startswith('/api/invitations') or request.path.startswith('/api/admin'):
            response.headers['Cache-Control'] = 'no-store'
            response.headers['Referrer-Policy'] = 'no-referrer'
        return response
